### ISSUE TITLE
Error: LIBUSB_ERROR_ACCESS when trying to claim the usb interface

### ISSUE THREAD

**Issue by jackkwong** [GoGoCodeJam/dream-cheeky-api#1]
/Users/jack/Documents/nodejs/dream-cheeky-driver/node_modules/usb/usb.js:139
    this.device.__claimInterface(this.id)
                ^
Error: LIBUSB_ERROR_ACCESS
    at Interface.claim (/Users/jack/Documents/nodejs/dream-cheeky-driver/node_modules/usb/usb.js:139:14)
    at Object.<anonymous> (/Users/jack/Documents/nodejs/dream-cheeky-driver/main.js:42:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by jackkwong** [comment]
actually, after increasing the debug level to 4, more useful error message come out:

jacks-MacBook-Pro:dream-cheeky-driver jack$ node main.js

> ## [timestamp] [threadID] facility level [function call] <message>
> 
> [ 0.012222] [00000507] libusb: debug [libusb_get_device_list]
> [ 0.012254] [00000507] libusb: debug [discovered_devs_append] need to increase capacity
> [ 0.012304] [00000507] libusb: debug [libusb_get_device_descriptor]
> [ 0.012354] [00000507] libusb: debug [libusb_get_device_descriptor]
> [ 0.012371] [00000507] libusb: debug [libusb_get_device_descriptor]
> [ 0.012387] [00000507] libusb: debug [libusb_get_device_descriptor]
> [ 0.012399] [00000507] libusb: debug [libusb_get_device_descriptor]
> [ 0.012410] [00000507] libusb: debug [libusb_get_device_descriptor]
> [ 0.012422] [00000507] libusb: debug [libusb_get_device_descriptor]
> [ 0.012433] [00000507] libusb: debug [libusb_get_device_descriptor]
> [ 0.012445] [00000507] libusb: debug [libusb_get_device_descriptor]
> [ 0.013084] [00000507] libusb: debug [libusb_open] open 20.5
> [ 0.013188] [00000507] libusb: debug [usbi_add_pollfd] add fd 15 events 1
> [ 0.013195] [00000507] libusb: debug [darwin_open] device open for access
> [ 0.013219] [00004203] libusb: debug [handle_events] poll() returned 1
> [ 0.013236] [00004203] libusb: debug [handle_events] caught a fish on the control pipe
> [ 0.013248] [00004203] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
> [ 0.013253] [00004203] libusb: debug [libusb_try_lock_events] someone else is modifying poll fds
> [ 0.013256] [00004203] libusb: debug [libusb_event_handler_active] someone else is modifying poll fds
> [ 0.013260] [00004203] libusb: debug [libusb_handle_events_timeout_completed] another thread is doing event handling
> [ 0.013284] [00004203] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
> [ 0.013290] [00004203] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
> [ 0.013294] [00004203] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
> [ 0.013647] [00000507] libusb: debug [libusb_kernel_driver_active] interface 0
> [ 0.013753] [00000507] libusb: debug [libusb_claim_interface] interface 0
> [ 0.014137] [00000507] libusb: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access
> [ 0.014145] [00000507] libusb: debug [libusb_claim_interface] interface 0
> [ 0.014456] [00000507] libusb: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access
> 
> /Users/jack/Documents/nodejs/dream-cheeky-driver/node_modules/usb/usb.js:139
>   this.device.__claimInterface(this.id)
>               ^
> Error: LIBUSB_ERROR_ACCESS
>    at Interface.claim (/Users/jack/Documents/nodejs/dream-cheeky-driver/node_modules/usb/usb.js:139:14)
>    at Object.<anonymous> (/Users/jack/Documents/nodejs/dream-cheeky-driver/main.js:42:21)
>    at Module._compile (module.js:456:26)
>    at Object.Module._extensions..js (module.js:474:10)
>    at Module.load (module.js:356:32)
>    at Function.Module._load (module.js:312:12)
>    at Function.Module.runMain (module.js:497:10)
>    at startup (node.js:119:16)
>    at node.js:906:3

Apparently, another process is using the device for exclusive access, even I unplug the missile launcher and plug it into another usb port...

**Comment by jackkwong** [comment]
[Tristil's comment](https://github.com/nonolith/node-usb/issues/30) might be the solution

**Comment by jackkwong** [comment]
confirmed, it's still usable even if `claim()` is not called

**Comment by maelswarm** [comment]
Has anyone found a fix to this?

**Comment by jackkwong** [comment]
@roecrew by my last testing, this issue should have been fixed (workaround by not calling `claim()`) in the latest version (`2.2.1`), or do you encounter this error message?
